### ISSUE TITLE
An easy way of getting the start and end points given a custom video

### ISSUE THREAD

**Issue by v-iashin** [wzmsltw/BSN-boundary-sensitive-network.pytorch#10]
Is there a way (or let's say a snippet) of getting predictions for a custom video?

Example signature:
`start_points, end_points = BSN(path_to_dir_with_video_frames)`

**Comment by v-iashin** [comment]
Ok, I guess, one should consider to do the inference using TSN first and then apply the BSN. Hence, there is no easy way.

**Comment by Ai-is-light** [comment]
@v-iashin have you solved this problem with some simple methods?

**Comment by v-iashin** [comment]
@Ai-is-light Nope, decided to work on something else.
