### ISSUE TITLE
Typo in initialization

### ISSUE THREAD

**Issue by hukkai** [wzmsltw/BSN-boundary-sensitive-network.pytorch#11]
Hello, in models.py line 28 (https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch/blob/e50d12953ec51c128360181afe69db37298f30d2/models.py#L28)
you used initialization in conv2d. But here it is conv1d. Also in PEM part the same issue.

**Comment by wzmsltw** [comment]
Thanks! So actually I just used default initialization ...
