### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by cinjon** [wzmsltw/BSN-boundary-sensitive-network.pytorch#13]
As far as I can tell, the training procedure with this repo is to first train the TEM, then generate the PGMs, then use those to train the PEM. Do you then repeat or do you do it just once?

**Comment by wzmsltw** [comment]
Yes, in BSN, first train the TEM, then generate the PGMs, then use those to train the PEM.
But I do not understand what you mean about " repeat or do you do it just once?"
