### ISSUE TITLE
Can i use BSN to separate video to multiple parts ?

### ISSUE THREAD

**Issue by ghost** [wzmsltw/BSN-boundary-sensitive-network.pytorch#15]
My video has different scenes.  
First, I want to cut my video to different parts , then i want to do scene classification on different parts of video . Can I use BSN to finish my first step ?

**Comment by wzmsltw** [comment]
Hi @tianlanli 
If you want to cut you video, actually I think KTS is a better solution.

**Comment by ghost** [comment]
> Hi @tianlanli
> If you want to cut you video, actually I think KTS is a better solution.

thank you, the full name of KTS is  Kernel temporal segmentation ?

**Comment by ghost** [comment]
is the KTS a software ?

**Comment by ghost** [comment]
I think i know  ,the KTS is put forward from Category-specific video summarization

**Comment by wzmsltw** [comment]
@tianlanli yes, KTS is Kernel temporal segmentation.
