### ISSUE TITLE
Evaluation on THUMOS14

### ISSUE THREAD

**Issue by VSunN** [wzmsltw/BSN-boundary-sensitive-network.pytorch#2]
Hi,
I want to know if the evaluation program is the same on the THUMOS14 dataset?

**Comment by wzmsltw** [comment]
@VSunN No, we use the official THUMOS14 detection evaluation codes. And proposal evaluation codes from https://gist.github.com/cabaf/9570df47f16ef7f79cb8cd8e3fa745d6

**Comment by Solaire-V** [comment]
Thanks,
Could you tell me the difference between the two evaluation programs? The AR@200 results obtained using the evaluation program you provided are much higher than the ActivityNet evaluation program.

**Comment by wzmsltw** [comment]
I guess it should be lower?  Evaluation codes of THUMOS using different theresholds [0.5:0.05:1.0] compared with activityNet [0.5:0.05:0.95].
