### ISSUE TITLE
TEM module

### ISSUE THREAD

**Issue by jesszgc** [wzmsltw/BSN-boundary-sensitive-network.pytorch#22]
Great job for action proposal.

        1, By reading your paper, i am wondering whether conv2d is better than conv1d in TEM module for action score regression?

       2, Can overlaping of slide windows in TEM feature sequence give us better scores?

looking forward for your reply!

**Comment by wzmsltw** [comment]
Hi @jesszgc , For first question, since tem handle the temporal feature sequence, I think only conv1d can be used. Actually, you can achieve conv1d with conv2d layer, but I think it will not bring furthur promotion. 2. Overlap of slide window can only bring little promotion.
