### ISSUE TITLE
ActivityNet AR@AN

### ISSUE THREAD

**Issue by cinjon** [wzmsltw/BSN-boundary-sensitive-network.pytorch#24]
Hi, do you have the results for Table 2 (https://arxiv.org/pdf/1806.02964.pdf) for ActivityNet? I am speaking of the @50, @100, ..., @1000 proposal recall numbers. I only see those reported for Thumos. Thanks.

**Comment by wzmsltw** [comment]
Hi @cinjon , I am sorry that I have not calculate AR@50 - AR@1000 recall number of other methods.  I only calculate AR@100 and AUC on ActivityNet.
