### ISSUE TITLE
feature sequence for THUMOS14 dataset

### ISSUE THREAD

**Issue by dreamedrainbow** [wzmsltw/BSN-boundary-sensitive-network.pytorch#28]
Hi，thx for the brilliant work！
I encounter a problem for using sliding window method in THUMOS14 dataset and I notice your reply in [Feature extraction questions #14](https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch/issues/14#issuecomment-524163172). I would be appreciate if you can send me codes of BSN in THUMOS14? My email address is rainbowdream1991@gmail.com. Thx again!

**Comment by curiosity654** [comment]
Hi, have you received the codes? Could you please send it to me as well？ Thx in advance.
My email is Curiosity654@outlook.com

**Comment by lsj9731** [comment]
Could you send me BSN-thumos codes ?
My email address: not12m10@gmail.com
Thank you !!

**Comment by Rui-hue** [comment]
Hi, have anyone received the code yet? Can you also send it to me? Thank you in advance.
My email address: [645249607@qq.com](mailto:645249607@qq.com)
