### ISSUE TITLE
Is oversample used for feature extraction?

### ISSUE THREAD

**Issue by Rheelt** [wzmsltw/BSN-boundary-sensitive-network.pytorch#3]
Thank you for your work! 
When I used TSN to extract features, I found oversample was used in the code, which results in the output of 'fc-action' being 10*200 (input being an image).
So I have to ask the following questions.
1, Whether oversample is used for feature extraction? If so, is the average taken at the end?
2, Or center-crop(w: 224 h: 224 c: 3) is adopted when extracting features in an image(340 256 3) or flow stack(340 256 10)?

**Comment by wzmsltw** [comment]
Hi, I used the caffe version of TSN and have not used the oversample before. And my old hard-drive is broken, I lost the feature extraction scripts, but I think I do not use crop during feature extraction
