### ISSUE TITLE
Can you provide me the classification results of ''cuhk & ethz & siat submission to activitynet challenge 2017''? Thanks very much.

### ISSUE THREAD

**Issue by zswzifir** [wzmsltw/BSN-boundary-sensitive-network.pytorch#6]

**Comment by wzmsltw** [comment]
please give me your email address

**Comment by zswzifir** [comment]
410301918@qq.com
Many thanks.

**Comment by shiyi001** [comment]
Hi~Tianwei Lin, could you send me the classification results of ActivityNet1.3 ? My email address is i_am_shiyi@163.com. Thank you very much!

**Comment by wzmsltw** [comment]
@shiyi001 have sent

**Comment by shiyi001** [comment]
@[wzmsltw](https://github.com/wzmsltw) Thanks a lot.

**Comment by odefiao** [comment]
I want to get the classification results of activitynet1.3 as well, could you send it to me, thank you so much @wzmsltw @zswzifir @shiyi001 
odefiao@gmail.com

**Comment by Sy-Zhang** [comment]
Hi Tianwei, I am also trying to get the detection results on activitynet. Could you send me a copy? Thanks a lot. hefeizsy@163.com.

**Comment by maodong2056** [comment]
@wzmsltw @zswzifir @shiyi001 @odefiao could you send the classification results of activitynet1.3 to me, thanks a lot 273270145@qq.com

**Comment by takfate** [comment]
@wzmsltw @zswzifir @shiyi001 @odefiao @maodong2056 @Sy-Zhang.
Could you send the classification results of activitynet1.3 to me?
Email:esxcg@outlook.com
Thanks a lot.

**Comment by lucky-23** [comment]
@wzmsltw @zswzifir  @shiyi001  @odefiao  @maodong2056  @Sy-Zhang  @takfate  Could you please send me the classification results of activitynet 1.3? I really need it for my research work. 
Email: lkeisham23@gmail.com
Thanks a lot.
