### ISSUE TITLE
pem_low_iou_thres default value

### ISSUE THREAD

**Issue by junyuseu** [wzmsltw/BSN-boundary-sensitive-network.pytorch#8]
In the opts.py, the 'pem_low_iou_thres' default value is 2.2. I suppose this is a small mistake. Do you mean 0.2 for this? 

####code#######
parser.add_argument(
        '--pem_low_iou_thres',
        type=float,
        default=2.2)
###############

Thanks.

**Comment by wzmsltw** [comment]
Yes.. It should be 0.2 actually.
